jenkinsci/pipeline-plugin

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/PushdStep.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverWriter.java
Cf. [JENKINS-26137](https://issues.jenkins-ci.org/browse/JENKINS-26137).
=> Make a test involving Jenkins restart pass

job/src/main/java/org/jenkinsci/plugins/workflow/job/AfterRestartTask.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
Needed for #37. @reviewbybees (especially @stephenc who added this new interface method)
=> Make a class compilable against core 1.592+.

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowJobNonRestartingTest.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java
[JENKINS-26541](https://issues.jenkins-ci.org/browse/JENKINS-26541)
@reviewbybees especially @kohsuke
=> [JENKINS-26541] Handle wrapped RejectedAccessException

.gitignore, job/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.jelly
Copy the Display Name configuration from the AbstractProject.
It is in AbstractItem, so it works without changing anything. The only thing missing was the configuration.
(Also I have to use Eclipse at work, so I added the .gitignore config for Eclipse)
=> Display Name configuration

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/StageTest.java, step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/StageStepExecution.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerCancelledCause.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/Rejection.java
Workaround until baseline is 1.591+. @reviewbybees (ref. ZD-24677)
=> Handle nonserializable causes of interruption

support/src/main/java/org/jenkinsci/plugins/workflow/support/storage/SimpleXStreamFlowNodeStorage.java
Minor memory optimization.
@reviewbybees (ref. ZD-24759)
=> Avoid storing an empty array in Tag.actions.

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepRestartTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepTest.java
Failed attempt at reproducing [JENKINS-26761](https://issues.jenkins-ci.org/browse/JENKINS-26761); useful to have test anyway to guard against other problems.
@reviewbybees
=> [JENKINS-26761] Verifying that polling still works after a restart

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/StageTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/StageStepExecution.java
[JENKINS-27052](https://issues.jenkins-ci.org/browse/JENKINS-27052)
@reviewbybees (ref. ZD-24784)
=> [JENKINS-27052] Stage.holding must track unblocked builds

CHANGES.md, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java, cps/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java, step-api/src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java, step-api/src/test/java/org/jenkinsci/plugins/workflow/structs/DescribableHelperTest.java, support/src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java
[JENKINS-25779](https://issues.jenkins-ci.org/browse/JENKINS-25779)
@reviewbybees
=> [JENKINS-25779] DescribableHelper.uninstantiate and default values

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/SleepStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/SleepStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/SleepStep/config.jelly, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/SleepStep/help.html, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java, step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
[JENKINS-26120](https://issues.jenkins-ci.org/browse/JENKINS-26120)
@reviewbybees
=> Sleep step

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly
[JENKINS-26123](https://issues.jenkins-ci.org/browse/JENKINS-26123)
Also threw in a fix for a related issue I saw in this code.
@reviewbybees
=> [JENKINS-26123] Non-blocking build trigger step

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
[JENKINS-26513](https://issues.jenkins-ci.org/browse/JENKINS-26513)
Guice-related error, sigh.
@reviewbybees
=> [JENKINS-26513] Deserialization error in ExecutorStepExecution

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepRestartTest.java
Observed in #62. @reviewbybees
=> Random test failure

cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/config.jelly, pom.xml
[JENKINS-25784](https://issues.jenkins-ci.org/browse/JENKINS-25784)
Needs a release of https://github.com/jenkinsci/script-security-plugin/pull/10
=> [JENKINS-25784] Defaulting of sandbox mode based on RUN_SCRIPT privs

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepRestartTest.java
#64 did not work, trying again. @reviewbybees
=> SCMTrigger.DescriptorImpl.synchronousPolling must be saved

CHANGES.md, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-quietPeriod.html, support/src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java
[JENKINS-26692](https://issues.jenkins-ci.org/browse/JENKINS-26692)
@reviewbybees
=> [JENKINS-26692] build step should allow specification of custom delay

cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/block.jelly
=> Snippetizer tweaks

scm-step/README.md, scm-step/pom.xml, scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/GitStep.java, scm-step/src/main/resources/org/jenkinsci/plugins/workflow/steps/scm/GitStep/config.jelly, scm-step/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepTest.java
[JENKINS-26085](https://issues.jenkins-ci.org/browse/JENKINS-26085)
=> [FIXED JENKINS-26085] Credentials support for git step

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/input/InputStepTest.java
See [this failure](https://jenkins.ci.cloudbees.com/job/plugins/job/workflow-plugin/org.jenkins-ci.plugins.workflow$workflow-aggregator/1031/testReport/junit/org.jenkinsci.plugins.workflow.steps.input/InputStepTest/test_cancel_run_by_input/) for example. @reviewbybees
=> @RandomlyFails

aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
[This](https://jenkins.ci.cloudbees.com/job/plugins/job/workflow-plugin/org.jenkins-ci.plugins.workflow$workflow-aggregator/1025/testReport/junit/org.jenkinsci.plugins.workflow/WorkflowTest/executorStepRestart/) for example. @reviewbybees
=> Random WorkflowTest.executorStepRestart failure on CI

aggregator/src/test/java/org/jenkinsci/plugins/workflow/BuildWatcher.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/JenkinsRuleExt.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/PersistenceFailureTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/SingleJobTestBase.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/SleepStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/StageTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/WorkspaceStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepRestartTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/RunWrapperTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/input/InputStepRestartTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Changes suggested in [JENKINS-25975](https://issues.jenkins-ci.org/browse/JENKINS-25975) and related issues.
@reviewbybees
=> Test improvements

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java, basic-steps/CORE-STEPS.md, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/CatchErrorStep/help.html
Correcting help text added in 5ade0f0d7e05e91e2db7a02c1486010c2db325e6. @reviewbybees and FYI @kohsuke
=> Corrected help text for catchError

cps/pom.xml
[JENKINS-27271](https://issues.jenkins-ci.org/browse/JENKINS-27271)
Just picking up an upstream fix. @reviewbybees
=> [JENKINS-27271] groovy-cps 1.3

aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, api/src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecutionList.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java
Some changes I made in #37 while diagnosing test failures which are not actually specific to that branch and could be useful earlier (without the core baseline change, etc.). @reviewbybees
=> Misc fixes

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java, support/src/test/java/org/jenkinsci/plugins/workflow/test/steps/SemaphoreStep.java
Fixes hard-to-diagnose test failures like one encountered in #37. @reviewbybees
=> Fix to SemaphoreStep semantics

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/ReadWriteFileStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/FileExistsStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/config.jelly, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help-file.html
This step verifies if a file exists in the workspace.
https://issues.jenkins-ci.org/browse/JENKINS-27474
=> [JENKINS-27474] Adding build step File Exists

support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/SecretPickle.java
Needed for [JENKINS-27631](https://issues.jenkins-ci.org/browse/JENKINS-27631). @reviewbybees
=> [JENKINS-27631] Added SecretPickle

step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/BodyInvoker.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/DefaultStepContext.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/SecretPickle.java
[JENKINS-27392](https://issues.jenkins-ci.org/browse/JENKINS-27392) subsumes #106. @reviewbybees
=> [JENKINS-27392] ConsoleLogFilter

TUTORIAL.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/MercurialStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/ReadFileStep.java
Follow-ups to #91 and 205f27b059414466f83ca4de7f99921c93336821. @reviewbybees
=> [JENKINS-27474] Noting a few places where fileExists would be useful

demo/Dockerfile, demo/JENKINS_HOME/hudson.tasks.Maven.xml
=> Updating Dockerfile

step-api/src/test/java/org/jenkinsci/plugins/workflow/steps/StepConfigTester.java
Commit comment explains why. @reviewbybees
=> Do not delete the test project from configRoundTrip while the test is running

CHANGES.md, durable-task-step/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java, pom.xml
Just using https://github.com/jenkinsci/durable-task-plugin/pull/5.
@reviewbybees
=> Call new Controller.stop overload

aggregator/src/test/java/org/jenkinsci/plugins/workflow/DSLTest.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsWhitelist.java
=> Make sure steps.echo('hi') syntax works inside the sandbox

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsGroovyShell.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovyShellDecorator.java
=> configureShell may also be called with a null context

CHANGES.md, COMPATIBILITY.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java, api/src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecution.java, basic-steps/CORE-STEPS.md, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep/config.jelly, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/AfterRestartTask.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution/PlaceholderTask/PlaceholderExecutable/executorCell.jelly
On the governance meeting today it was agreed that the next LTS will be based on 1.609. I have set up a base branch `lts-609` (rooted at `master`), to be merged back into `master` at some later date no earlier than the appearance of 1.609.1; and am proposing to merge some feature PRs into it:
* https://github.com/jenkinsci/workflow-plugin/pull/37 (required 1.599+)
* https://github.com/jglick/workflow-plugin/pull/1 (required 1.609+)
* https://github.com/jenkinsci/workflow-plugin/pull/95 (required 1.607+)
@reviewbybees
=> Prepare features for 1.609.x

pom.xml
=> Use FindBugs plugin 3.0.1

cps-global-lib/src/main/java/org/jenkinsci/plugins/workflow/cps/global/GroovyShellDecoratorImpl.java
=> File.toURL is deprecated

demo/Makefile
=> Need to pass --rm to docker-run.

demo/Makefile
=> Need to also push the latest tag.

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/EnvStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/EnvStep.java
=> withEnv clobbered environment variables set in enclosing steps

aggregator/pom.xml, api/pom.xml, basic-steps/pom.xml, cps-global-lib/pom.xml, cps/pom.xml, durable-task-step/pom.xml, job/pom.xml, pom.xml, scm-step/pom.xml, step-api/pom.xml, stm/pom.xml, support/pom.xml
[Discussion](https://groups.google.com/d/msg/jenkinsci-dev/oEHEjKo08yA/ShbomKaaA7QJ)
@reviewbybees
=> Switching to wiki page as the plugin URL

CHANGES.md, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java, job/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.jelly
[JENKINS-26860](https://issues.jenkins-ci.org/browse/JENKINS-26860)
@reviewbybees
=> [JENKINS-26860] WorkflowJob.concurrentBuild

TUTORIAL.md
Typos etc. found during a first reading of TUTORIAL.md
(WIP)
=> Minor changes to TUTORIAL.md

aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowRunTest.java
@reviewbybees but this is for @harniman who claimed it did not work (AFAICT it does).
=> Checking that binding['name'] syntax works for parameters

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/AvailableEnvVarTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
https://issues.jenkins-ci.org/browse/JENKINS-28131
=> [JENKINS-28131] - Pass NODE_NAME into node{}

COMPATIBILITY.md
It hasn't been released yet, but it has been merged in.
=> Add Scoverage plugin to list of supported plugins.

pom.xml
=> Enable FindBugs in workflow parent pom

COMPATIBILITY.md
Add compatibility for BitBucket trigger in Workflow
I am already working on it in [JENKINS-28882](https://issues.jenkins-ci.org/browse/JENKINS-28882)
@reviewbybees
=> Add compatibility for BitBucket trigger in Workflow

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowRunTest.java, api/src/main/java/org/jenkinsci/plugins/workflow/flow/FlowExecution.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java, cps/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
[JENKINS-29571](https://issues.jenkins-ci.org/browse/JENKINS-29571)
If the existence of this bug a year in is not sufficient evidence of the need for QA, I am not sure what is…@reviewbybees but esp. @kohsuke whose exotic `unmarshal` implementation this was.
=> [JENKINS-29571] Handle build records after rename

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
=> [JENKINS-29221] Further cleanup for builds that fail to start

aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/ExecutorStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java, step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecutionCallback.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java, support/src/test/java/org/jenkinsci/plugins/workflow/test/steps/TmpDirStepExecution.java
Suggested by @kohsuke in a PR some months ago; finally got around to writing it.
@reviewbybees
=> Introduced BodyExecutionCallback.TailCall

support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help-parameters.html
=> Documenting the return value of the input step

basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactUnarchiverStepExecution.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverWriter.java
=> Removing a couple unwanted references to com.trilead.ssh2.util.IOUtils.closeQuietly

support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/POSTHyperlinkNote.java
https://issues.jenkins-ci.org/browse/JENKINS-29890
=> [JENKINS-29890] Submitter of an InputStep is not logged if approval made from the console

demo/repo/Jenkinsfile
=> Fixed a longstanding issue with the demo

aggregator/src/test/java/org/jenkinsci/plugins/workflow/CpsScmFlowDefinitionTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowRunTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/ExecutorStepTest.java, api/src/main/java/org/jenkinsci/plugins/workflow/graph/FlowGraphWalker.java, cps/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/views/FlowGraphAction.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/views/GraphVizAction.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/visualization/table/FlowGraphTable.java
Add ```Iterable``` capabilities to ```FlowGraphWalker```
=> Iterable FlowGraphWalker

cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/block.jelly
[JENKINS-29653](https://issues.jenkins-ci.org/browse/JENKINS-29653)
@reviewbybees
=> [JENKINS-29653] Added a little vertical space between  button and the textarea

multibranch/pom.xml, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
https://github.com/jenkinsci/subversion-plugin/pull/129 now fixed.
@reviewbybees and thanks @recena for getting the release out the door.
=> Test against Subversion 2.5.2

TUTORIAL.md, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
Groovy CPS DSL means not a lot to most, and to those who do know that TMA means, they already know it, so they don't need to be told it. flow.groovy should be "workflow script"
=> Workflow script is a proud first class citizen - own it

api/src/main/java/org/jenkinsci/plugins/workflow/visualization/table/FlowNodeViewColumnDescriptor.java, step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/Step.java
=> Neglected to mark all ExtensionPoint interfaces in Workflow

CHANGES.md, cps/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
[JENKINS-29739](https://issues.jenkins-ci.org/browse/JENKINS-29739)
@reviewbybees
=> [JENKINS-29739] Snippet generation broken for single-parameter jobs

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly, support/src/main/java/org/jenkinsci/plugins/workflow/support/actions/EnvironmentAction.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/RunWrapper.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-wait.html
[JENKINS-29169](https://issues.jenkins-ci.org/browse/JENKINS-29169)
@reviewbybees
=> Downstream flow build variables

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java
[Question](http://stackoverflow.com/questions/32228590/start-a-job-multiple-times-concurrently-with-workflow-plugin)
Note that it is hard for the `build` step to differentiate between `ScheduleResult.Created` and `.Existing`, which is the first step in diagnosing the mistake, since both return non-null from `getItem()` and `ParameterizedJobMixIn.scheduleBuild2` does not give access to the underlying `ScheduleResult`. Unfortunately I neglected to correct this mistake in https://github.com/jenkinsci/jenkins/pull/1771 so it is still not possible with a 1.623 core dependency (without copying & pasting a bunch of code from `ParameterizedJobMixIn`). Probably need yet another core patch to get it right.
@reviewbybees
=> Demonstrating that it is possible to build the same downstream project several times concurrently

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowParameterDefinitionBranchPropertyTest.java
[JENKINS-30206](https://issues.jenkins-ci.org/browse/JENKINS-30206)
Did not manage to reproduce any problem from a test.
@reviewbybees
=> [JENKINS-30206] Testing WorkflowParameterDefinitionBranchProperty more

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/DeleteDirStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/DeleteDirStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/DeleteDirStep/config.jelly, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/DeleteDirStep/help.html
Added a new step (deleteDir) which will wipe out the current directory in a workspace.
[JENKINS-30346](https://issues.jenkins-ci.org/browse/JENKINS-30346)
@reviewbybees
=> [FIXED JENKINS-30346] Added a deleteDirStep to wipe out a directory

support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-job.html
=> Added help for BuildTriggerStep.job

TUTORIAL.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
=> Better document and test @NonCPS

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java, job/src/main/resources/org/jenkinsci/plugins/workflow/job/Messages.properties
[JENKINS-30974](https://issues.jenkins-ci.org/browse/JENKINS-30974)
@reviewbybees
=> [JENKINS-30974] Fix potential `NoSuchMethodError` on 1.625

multibranch/pom.xml, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/GitDirectorySCMNavigator.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowParameterDefinitionBranchPropertyTest.java, multibranch/src/test/resources/org/jenkinsci/plugins/multirepo/workflow/GitDirectorySCMNavigator/config.jelly
Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/8.
@reviewbybees esp. @stephenc
=> WorkflowMultiBranchProjectFactory

COMPATIBILITY.md
[Log Parser Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Log+Parser+Plugin) is now compatible with Workflow Plugin.
/cc @jglick
=> [JENKINS-27208] Compatibility listing updated

support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-wait.html
=> @NonCPS, not @NonCps

CHANGES.md, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/RunWrapper.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-wait.html
=> Added absoluteUrl property to RunWrapper

pom.xml
... and deprecated configuration removed.
=> Findbugs dependency has beed updated.

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
Tests https://github.com/jenkinsci/branch-api-plugin/pull/11.
@reviewbybees
=> Verifying that MultiBranchProject.BranchSourceList works

multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/12.
@reviewbybees esp. @stephenc, @recena
=> [JENKINS-30252] Verifying that ${env.BRANCH_NAME} works

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/4 and https://github.com/jenkinsci/branch-api-plugin/pull/13.
@reviewbybees esp. @stephenc, @recena, @amuniz
=> [JENKINS-30595] Tested API

aggregator/src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
[JENKINS-31314](https://issues.jenkins-ci.org/browse/JENKINS-31314)
@reviewbybees
=> [JENKINS-31314] Demonstrating problem in test

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java, multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/SCMVar/help.jelly, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
[JENKINS-30531](https://issues.jenkins-ci.org/browse/JENKINS-30531)
@reviewbybees esp. @stephenc, @recena
=> [JENKINS-30531] Set SCMRevisionAction when we do a build

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java, job/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.jelly, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java, multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/SCMBinder/config.jelly
[JENKINS-30530](https://issues.jenkins-ci.org/browse/JENKINS-30530)
@reviewbybees
=> [JENKINS-30530] Display SCMBinder

multibranch/pom.xml, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java
Downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/23.
@reviewbybees esp. @stephenc
=> [JENKINS-31129] Adapting test to behavioral change

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactoryTest.java
Tests https://github.com/jenkinsci/branch-api-plugin/pull/14.
@reviewbybees esp. @stephenc
=> Testing restricted View permissions

cps/gulpfile.js, cps/pom.xml, cps/src/main/js/samples.js, cps/src/main/js/workflow-editor.js
Follow-up to #234
@reviewbybees
=> ACE Editor tweaks

cps-global-lib/README.md
Mismatch between parameter and variable names - fixed it to be "name"
in both places.
@reviewbybees
=> helloWorld global example didn't actually work.

demo/Dockerfile
Alternative to #250.
@reviewbybees esp. @amuniz
=> Switched Jetty download site

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/input/InputStepTest.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly, support/src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java
@jglick hopefully these fix your issues on that branch.
=> Fixes for post-625

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Might seem obvious but I've already had many people *not* clicking on
the link thinking this was only something informational.
=> [JENKINS-25550] Make it clearer it's a clickable link

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/IsUnixStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/IsUnixStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/IsUnixStep/config.jelly, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/IsUnixStep/help.html
[JENKINS-31691](https://issues.jenkins-ci.org/browse/JENKINS-31691)
@reviewbybees esp. @jtnord
=> [JENKINS-31691] isUnix step

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/ExecutorStepTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
[JENKINS-31649](https://issues.jenkins-ci.org/browse/JENKINS-31649?focusedCommentId=242436&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242436)
Integrates with https://github.com/jenkinsci/jenkins/pull/1919.
@reviewbybees esp. @stephenc, @varmenise
=> [JENKINS-31649] Integrate with post-SECURITY-186 queue item display policy

support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-excludes.html, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-includes.html
=> Improve documentation for stash step

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitSampleRepoRule.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
[JENKINS-31884](https://issues.jenkins-ci.org/browse/JENKINS-31884)
Fails in 2.4.0+.
@reviewbybees
=> [JENKINS-31884] Integration test for Git webhooks in multibranch projects

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
[JENKINS-29413](https://issues.jenkins-ci.org/browse/JENKINS-29413)
@reviewbybees
=> [JENKINS-29413] Hung build when running the parallel step with an empty map

CHANGES.md, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition/config.jelly, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition/help-scriptPath.html, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java, multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/SCMVar/help.jelly, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMVarTest.java
[JENKINS-31386](https://issues.jenkins-ci.org/browse/JENKINS-31386)
@reviewbybees esp @abayer
=> [JENKINS-31386] Standalone support for checkout scm

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/CpsScmFlowDefinitionTest.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
[JENKINS-29881](https://issues.jenkins-ci.org/browse/JENKINS-29881)
cc @reviewbybees
=> [JENKINS-29881] Don't include empty changesets in getChangeSets()

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactoryTest.java
[JENKINS-29603](https://issues.jenkins-ci.org/browse/JENKINS-29603) should not affect multibranch (AFAICT) so https://github.com/jenkinsci/git-plugin/pull/369 is not needed to support [JENKINS-30744](https://issues.jenkins-ci.org/browse/JENKINS-30744).
@reviewbybees & FYI @MarkEWaite
=> Extend JENKINS-30744 test to confirm that it is unaffected by JENKINS-29603

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
[JENKINS-31897](https://issues.jenkins-ci.org/browse/JENKINS-31897)
@reviewbybees
=> [JENKINS-31897] Set default parameters on build calls

cps/src/main/js/workflow-editor.js
[JENKINS-31909](https://issues.jenkins-ci.org/browse/JENKINS-31909)
@reviewbybees
=> [JENKINS-31909] Show groovy syntax validation message

COMPATIBILITY.md
=> [JENKINS-27718] Noting

COMPATIBILITY.md
Ansible plugin is compatible since version 0.4
=> [JENKINS-30398] Updating COMPATIBILITY.md

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepTest.java, pom.xml
=> Moving to git plugin 2.4.1 and enabling test for JENKINS-29326

cps/package.json, cps/pom.xml
=> [JENKINS-32317] Silence annoying NPM warnings

CHANGES.md, api/src/main/java/org/jenkinsci/plugins/workflow/pickles/Pickle.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/TryRepeatedly.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
[JENKINS-31614](https://issues.jenkins-ci.org/browse/JENKINS-31614)
Trying to cover all three known cases.
@reviewbybees
=> [JENKINS-31614] Avoid acquiring the Queue lock while holding other locks

COMPATIBILITY.md
=> Add Integrations for Coverity, Ownership and JobRestrictions plugins to the wishlist

CHANGES.md, cps/pom.xml
[JENKINS-32062](https://issues.jenkins-ci.org/browse/JENKINS-32062)
@reviewbybees
=> [JENKINS-32062] Integrate groovy-cps 1.6

support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/Messages.properties
[JENKINS-31878](https://issues.jenkins-ci.org/browse/JENKINS-31878)
@reviewbybees
=> [JENKINS-31878] What I hope is clearer wording

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/EchoStepTest.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Corrects a regression in #213.
@reviewbybees
=> [JENKINS-27057] Doubled-up log text

COMPATIBILITY.md
=> Adding xunit to compatibility list

aggregator/src/test/java/org/jenkinsci/plugins/workflow/BuildQueueTasksTest.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/AfterRestartTask.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
[JENKINS-28649](https://issues.jenkins-ci.org/browse/JENKINS-28649). Supersedes #137 
@reviewbybees
=> [JENKINS-28649] Add exported beans needed for Queue API

aggregator/pom.xml, api/pom.xml, basic-steps/pom.xml, cps-global-lib/pom.xml, cps/pom.xml, durable-task-step/pom.xml, job/pom.xml, multibranch/pom.xml, pom.xml, scm-step/pom.xml, step-api/pom.xml, stm/pom.xml, support/pom.xml
As part of [JENKINS-31153](https://issues.jenkins-ci.org/browse/JENKINS-31153)
@reviewbybees
=> [JENKINS-31153] WikiPage URL renamed

aggregator/src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/ScalabilityTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/EchoStepTest.java
Observed flakes.
@reviewbybees
=> Miscellaneous test failures

COMPATIBILITY.md, README.md, TUTORIAL.md, aggregator/src/main/resources/index.jelly, api/src/main/resources/index.jelly, basic-steps/CORE-STEPS.md, basic-steps/src/main/resources/index.jelly, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/CatchErrorStep/help.html, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/CoreStep/help.html, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep/help.html, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/SleepStep/help.html, cps-global-lib/README.md, cps-global-lib/src/main/resources/index.jelly, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStep.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/help-script.html, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition/help-scm.html, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/steps/LoadStep/help.html, demo/Dockerfile, demo/JENKINS_HOME/log/Workflow.xml, demo/README.md, job/src/main/java/org/jenkinsci/plugins/workflow/job/console/WorkflowConsoleLogger.java, multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep/help.html, multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/SCMVar/help.jelly, scm-step/README.md, scm-step/src/main/resources/org/jenkinsci/plugins/workflow/steps/scm/GenericSCMStep/help.html, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/StageStep/help.html, support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help.html
Things forgotten in #296.
@reviewbybees
=> [JENKINS-31153] More renames

pom.xml
Experimental Parent POM used: https://github.com/andresrc/plugin-pom
Won't build as cannot fetch parent POM (unreleased).
DO NOT MERGE.
@reviewbybees esp. @jglick and @stephenc
=> Experimental cleanup using new plugin parent POM

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
A few things I observed and was able to track down at least partially.
@reviewbybees
=> Flaky tests

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java, pom.xml
Obsolete test ignores.
@reviewbybees
=> All tests pass after use of jenkins-test-harness 2.0

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/ExecutorStepTest.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
[JENKINS-30759](https://issues.jenkins-ci.org/browse/JENKINS-30759)
@reviewbybees
=> [JENKINS-30759] Race condition initializing fields in RunningTask

demo/plugins.txt, multibranch/pom.xml, multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java, multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
Mainly adapting to https://github.com/jenkinsci/branch-api-plugin/pull/24.
@reviewbybees
=> branch-api 1.1

COMPATIBILITY.md
Add PerformancePublisher https://issues.jenkins-ci.org/browse/JENKINS-32650
=> Add PerformancePublisher

api/src/main/java/org/jenkinsci/plugins/workflow/actions/NotExecutedNodeAction.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/storage/SimpleXStreamFlowNodeStorage.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/visualization/table/FlowGraphTable.java
=> PR 333 fixups for `NotExecutedNodeAction`

COMPATIBILITY.md
=> [JENKINS-32801]Request Zephyr compatibility

cps/src/main/js/workflow-editor.js
[JENKINS-32819](https://issues.jenkins-ci.org/browse/JENKINS-32819)
@reviewbybees
=> [JENKINS-32819] Fix script compilation check when CSRF is enabled

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepTest.java, scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/GitStep.java
Allows local commits where desired.
@reviewbybees esp. @cyrille-leclerc
=> From the simple git step, always check out to a local branch

COMPATIBILITY.md
Also fixed the performance plugin checkbox.
=> Adding publish-over-ssh to COMPATIBILITY.md.

CHANGES.md, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java, cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java, support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/StageStepExecution.java
[JENKINS-33005](https://issues.jenkins-ci.org/browse/JENKINS-33005)
@reviewbybees
=> [JENKINS-33005] Hang in StageStepExecution.println

COMPATIBILITY.md
don't know if i should name the other 5 builders PerfSigStart/Stop Recording, PerfSigActivateConfiguration, PerfSigMemory/Thread Dump
=> Adding performance-signature-dynatrace to COMPATIBILITY.md

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/SubversionStepTest.java, job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
Replaces #284. [JENKINS-32214](https://issues.jenkins-ci.org/browse/JENKINS-32214)
@reviewbybees
=> [JENKINS-32214] Polling baseline with in-progress builds

CHANGES.md, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/PwdStepTest.java, basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/PwdStep.java, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/PwdStep/config.jelly, basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/PwdStep/help-tmp.html
Corresponds to https://github.com/jenkinsci/jenkins/pull/2066 etc.
@reviewbybees
=> [JENKINS-27152] Option for pwd step to return temp directory

multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java
Works in tandem with https://github.com/jenkinsci/branch-api-plugin/pull/29.
@reviewbybees
=> Export the Branch & SCM to REST

aggregator/pom.xml, aggregator/src/main/resources/index.jelly, multibranch/pom.xml, multibranch/src/main/resources/index.jelly
Among other places, this shows up in the setup wizard to explain what this plugin is.
@reviewbybees
=> Added description

COMPATIBILITY.md
Slack supports Jenkins Pipeline as of version 2.0
=> [JENKINS-27652] Workflow support for Slack Notifications

COMPATIBILITY.md
https://issues.jenkins-ci.org/browse/JENKINS-31801
@reviewbybees @abayer
=> Add throttle-concurrent-builds plugin to the list

cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/dslReferenceContent.groovy, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/dsld.groovy, cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/gdsl.groovy, cps/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java, step-api/pom.xml, step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java, step-api/src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java, support/src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java
`DescribableHelper` functionality has moved to structs plugin, in preparation for the death of `$class`
=> Using structs plugin

support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep/help-label.html
Copies [this text](https://github.com/jenkinsci/jenkins/blob/35ec989afffcbafbd6b29443968e6461f82b302d/core/src/main/resources/hudson/model/AbstractProject/help-label.html#L11-L51) for now.
@markhu asked on #jenkins about this.
@reviewbybees
=> Add more detailed help for ExecutorStep.label

cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/dslReferenceContent.groovy
Use stack to keep track of traversal.
Counter proposal to https://github.com/jenkinsci/structs-plugin/pull/1
@reviewbybees in particular @kwhetstone
=> [JENKINS-32925] Handle recursion

job/src/test/java/org/jenkinsci/plugins/workflow/ReverseBuildTriggerTest.java
Downstream of https://github.com/jenkinsci/jenkins/pull/2207.
@reviewbybees esp. @fbelzunc
=> [JENKINS-33971] Integration test for ReverseBuildTrigger.upstream2Trigger bug

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
downstream of https://github.com/jenkinsci/jenkins/pull/2217
@reviewbybees especially @jglick and @daniel-beck
=> Category ID has changed

COMPATIBILITY.md
https://wiki.jenkins-ci.org/display/JENKINS/Exclusion-Plugin
CC @jglick
=> Add Exclusion-Plugin to the list

COMPATIBILITY.md
=> Adding Powershell to compat list

COMPATIBILITY.md
Adding completion check for Build Failure Analyzer
=> [JENKINS-27123] Update COMPATIBILITY.md

aggregator/pom.xml, aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java, aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/MercurialStepTest.java, api/pom.xml, basic-steps/pom.xml, cps-global-lib/pom.xml, cps/pom.xml, durable-task-step/pom.xml, job/pom.xml, pom.xml, scm-step/pom.xml, scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/GitStep.java, scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/SubversionStep.java, step-api/pom.xml, support/pom.xml
Backport of #389 to support https://github.com/jenkinsci/subversion-plugin/pull/161.
@reviewbybees
=> [JENKINS-35247] Delegate to Git and Subversion plugins via reflection (1.4.x)

scm-step/pom.xml, scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/GitStep.java, scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/SubversionStep.java
Preparing a new baseline for https://github.com/jenkinsci/git-plugin/pull/406 that should avoid a cyclic dependency error.
@reviewbybees
=> [JENKINS-35247] Delegate to Git and Subversion plugins via reflection (1.14.x)

TUTORIAL.md
direction for find add maven option under jenkins 2.x
=> jenkins 2.x specific direction

.idea/vcs.xml, COMPATIBILITY.md
Added BitbucketBuildStatusNotifier to COMPATIBILITY.md
=> Added BitbucketBuildStatusNotifier

COMPATIBILITY.md
[JENKINS-34981](https://issues.jenkins-ci.org/browse/JENKINS-34981)
=> [JENKINS-34981] Add valgrind-plugin to COMPATIBILITY.md

DEVGUIDE.md, TUTORIAL.md
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/35.
@reviewbybees esp. @kohsuke, @abayer
=> [JENKINS-29922] Documentation update

TUTORIAL.md
@jglick 
We're moving to using "agent" instead of "slave".
=> Change "slave" to "agent"

COMPATIBILITY.md
cucmber test reports now supports pipeline
=> [JENKINS-26340] Update COMPATIBILITY.md

COMPATIBILITY.md
=> Update COMPATIBILITY.md: jobconfighistory already supports pipeline

COMPATIBILITY.md
Updated COMPATIBILITY.md to reflect compatibility status of HockeyApp Plugin
=> [JENKINS-33310] reflected compatibility status of HockeyApp Plugin

COMPATIBILITY.md
=> mark StashNotifier as supported and link to docs

COMPATIBILITY.md
=> [JENKINS-28454] Add WsCleanup to compatible steps

COMPATIBILITY.md
=> [JENKINS-40624] Update COMPATIBILITY.md to update NodeJS plugin

COMPATIBILITY.md
Implemented in 0.7.10
Added Databound Setters and set isApplicable to true.
https://github.com/jenkinsci/accurev-plugin/blob/master/src/main/java/hudson/plugins/accurev/AccurevSCM.java
=> Add AccuRev compatibilty

COMPATIBILITY.md
Refs:
* https://github.com/jenkinsci/jacoco-plugin/pull/66#issuecomment-267657781
* https://github.com/jenkinsci/jacoco-plugin/blob/jacoco-2.1.0/src/main/java/hudson/plugins/jacoco/JacocoPublisher.java#L46
=> Fix step name for JacocoPublisher

COMPATIBILITY.md
=> [JENKINS-36570] - Add PrioritySorter to the Pipeline Compatibility list

CONTRIBUTING.md, README.md, TUTORIAL.md
Mainly linking to jenkins.io.
@reviewbybees
=> Updating or removing some content

COMPATIBILITY.md
https://github.com/jenkinsci/cobertura-plugin/pull/55
@reviewbybees
=> [JENKINS-30700] Noting cobertura fix
