jenkinsci/pipeline-plugin

basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepExecution.java

Original code was @kohsuke’s; probably just an unexamined copy-and-paste from `hudson.tasks.ArtifactArchiver`, which _does_ need to make this call.

Do not call EnvVars.expand from ArtifactArchiverStepExecution

---

pom.xml

(mvn -DskipTests clean install)
without this fix the build fails with this error:
[ERROR]     Unresolveable build extension: Plugin org.jenkins-ci.tools:maven-hpi-plugin:1.110 or one of its dependencies could not be resolved: Could not find artifact org.jenkins-ci.tools:maven-hpi-plugin:jar:1.110 in central (http://repo.maven.apache.org/maven2) -> [Help 2]
[ERROR]

simple build fails without correct plugin repositories listed 

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/SubversionStepTest.java

If the SCM tools are not installed (subversion/mercurial) then don't fail the unit tests.
@reviewbybees

Skip unit tests when required tooling (hg, svn) is not installed.

---

cps/src/test/groovy/org/jenkinsci/plugins/workflow/cps/CpsScriptTest.groovy

Noticed when doing a full build. Cause of failure unknown; passed the next time. @reviewbybees

@RandomlyFails

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java

Observed once to fail saying that the build status was `null` rather than `FAILURE`, perhaps because the flow had suspended and was just about to complete but had not done so yet.
@reviewbybees

Random test failure

---

CHANGES.md
support/src/main/resources/org/jenkinsci/plugins/workflow/support/actions/LogActionImpl/index.jelly
support/src/main/resources/org/jenkinsci/plugins/workflow/support/actions/LogActionImpl/index.properties

[JENKINS-26605](https://issues.jenkins-ci.org/browse/JENKINS-26605)
@reviewbybees

[JENKINS-26605] LogActionImpl was missing a definition of skipSome

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java

Previously was marking a build as failed when it was merely supposed to be canceled due to a superseded stage, etc.
@reviewbybees (ref. ZD-24677)

Handle FlowInterruptedException from CatchErrorStep

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/CpsFlowExecutionTest.java
cps/pom.xml
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java

When running a flow repeatedly, the `WorkflowScript` (a dynamic `CpsScript` subclass) is not promptly collected, nor is its `GroovyClassLoader.InnerLoader` and thus an assortment of derivative classes and objects. Demo:
```bash
jmap -histo $pid | fgrep WorkflowScript | wc -l
```
prints the number of builds you have just run. (Note that each line is a class called `WorkflowScript` from its own class loader.)
I think I have fixed all the hard-reference leaks, so Jenkins will collect the remaining `SoftReference`s under heavy memory pressure rather than throwing an `OutOfMemoryError`; to demo, using the current patch run in `/script`
```groovy
for (i = 1; ; i *= 2) {
System.gc();
new Object[i];
}
```
and the `WorkflowScript` count will drop to 0. Sometimes this also happens after merely …

Memory leaks

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodySubContext.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java

[JENKINS-25890](https://issues.jenkins-ci.org/browse/JENKINS-25890)
Reproduced by a revision of the test added in #62.
Removing the exceptions from the declaration of `isReady` to emphasize that it is not intended to block.
@reviewbybees esp. @kohsuke

[JENKINS-25890] Deadlock

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java

[JENKINS-25890](https://issues.jenkins-ci.org/browse/JENKINS-25890)
Amends fix in #65. That turned out to cause `WorkflowTest.acquireWorkspace` to fail mostly reliably—it was already `@RandomlyFails`—one reason why a PR from @jtnord to use the “flaky test” feature of Surefire would be appreciated.
The problem was that rehydration of pickles via `TryRepeatedly` depends on `jenkins.util.Timer`, which is a cached thread pool with 10 threads, yet the original fix added a task to this same pool for a couple of commonly used `CpsStepContext` methods. These tasks would block waiting for the program to load, which cannot happen until all the pickles are rehydrated. Of the twelve pickles loaded in this test (six per loaded build), ten got rehydrated fine, but the last two were `ExecutorPickle`s, …

[JENKINS-25890] Use own thread pool for CpsStepContext.getProgramPromise

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/input/InputStepTest.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java

See [JENKINS-26363](https://issues.jenkins-ci.org/browse/JENKINS-26363)
Also moved `InputStep.canSubmit` and `InputStep.canSettle` to `InputStepExecution` (and made them private there). I deprecated those methods in `InputStep` i.e. didn't remove them in case they are somehow in use from outside. Can remove them if we think they're not.

[FIXED JENKINS-26363] Input step should permit cancellation from anyone with Job.CANCEL permission

---

support/src/main/java/org/jenkinsci/plugins/workflow/support/actions/WorkspaceActionImpl.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/FilePathPickle.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java

Hoping this is enough to fix [JENKINS-25958](https://issues.jenkins-ci.org/browse/JENKINS-25958). Is there a way we can easily test this?
@reviewbybees

[FIXED JENKINS-25958] Check for already known Computers/Channels in FilePathPickle.Listener

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
cps/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
step-api/src/test/java/org/jenkinsci/plugins/workflow/structs/DescribableHelperTest.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/StaplerReferer.java
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/DescriptorImpl/parameters.groovy
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly

Part of [JENKINS-26093](https://issues.jenkins-ci.org/browse/JENKINS-26093) so far.
@reviewbybees

[JENKINS-26093] Better support for build step parameters

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepRestartTest.java

Observed:
```
java.lang.AssertionError: expected:<1> but was:<2>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at org.jenkinsci.plugins.workflow.steps.build.BuildTriggerStepRestartTest$2.evaluate(BuildTriggerStepRestartTest.java:53)
```
(Naturally, by Murphy’s law, this was during `release:prepare`; never saw it before.)
I suspect the mystery second queue item was a `org.jenkinsci.plugins.workflow.job.AfterRestartTask`, which should only be in the queue for a moment, because it is a `FlyweightTask` and should be scheduled as soon as `Queue.maintain` is called, but perhaps the second step of the …

Another random test failure

---

CHANGES.md
step-api/pom.xml
step-api/src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
step-api/src/test/java/org/jenkinsci/plugins/workflow/structs/DescribableHelperTest.java

[JENKINS-26619](https://issues.jenkins-ci.org/browse/JENKINS-26619)
The Snippet Generator (`uninstantiate`) was confused by `GitSCMExtension`s (leaving raw objects in the suggested snippet) because `GitSCM` declares the constructor parameter as a plain old `List` whereas the getter is a `DescribableList`. `DescribableHelper` provides special treatment for JSONish lists when they could be assigned to a virtual field of `List` or `Collection` type (here is where #61 went astray), which was skipped in this case because it was seeing the field type as `DescribableList`—too narrow. But `List` was what we needed for `uncoerce` to map the `List<GitSCMExtension>` back to a JSONish list (something like `ListGitSCMExtension<Map<String,?>>`), and in fact is more relevant since ultimately …

[JENKINS-26619] GitSCM.extensions reflection fix

---

cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/help-script.html

See [JENKINS-27145](https://issues.jenkins-ci.org/browse/JENKINS-27145).
Please check the variables I listed as not being available outside a `node`. And if there are other exceptions that should be noted in the text help.

[JENKINS-27145] Linking to env-vars.html from UI

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/WorkspaceStepTest.java
cps/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepExecution.java
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep/config.jelly
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep/help-dir.html

[JENKINS-26072](https://issues.jenkins-ci.org/browse/JENKINS-26072)
While this sounds similar to `AbstractProject.customWorkspace`, that only selects an alternate directory to run the build in, and does no locking whatsoever, which you could already do in a Workflow with `dir`.
@reviewbybees

[FIXED JENKINS-26072] Specify alternate path to lock in WorkspaceStep

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java
api/src/main/java/org/jenkinsci/plugins/workflow/actions/BodyExecutionLabelAction.java
api/src/main/java/org/jenkinsci/plugins/workflow/actions/ThreadNameAction.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

See [JENKINS-26122](https://issues.jenkins-ci.org/browse/JENKINS-26122)
Prefixes log entries from the `parallel` step using the branch name. Added `BodyExecutionLabelAction` (currently located in the `workflow-api` module, which seems wrong ... see comment in `BodyExecutionLabelAction`) and modified `ParallelLabelAction` to extend it.
Example output - see the `[a]` and `[b]` prefixes on some of the log lines in the following sample.
```
Started by user anonymous
Running: Allocate node : Start
Running on master in /Users/tfennelly/projects/jenkins-plugins/workflow-plugin/aggregator/work/jobs/Workflwo/workspace
Running: Allocate node : Body : Start
Running: Execute sub-workflows in parallel : Start
[a] Running: Parallel branch: a
[b] Running: Parallel branch: b
[a] Running: Print Message …
```

[JENKINS-26122] Prepend parallel step execution logs with the branch label

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/input/InputStepTest.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/ApproverAction.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/ApproverAction/summary.jelly
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/ApproverAction/summary.properties

This solves https://issues.jenkins-ci.org/browse/JENKINS-26121.
The input step now records and shows who approved the request.
However, if you are NOT logged in and try to approve, you are prompted with the error message which says "you need to be X to submit".
if you log in, then you are asked to "try POST" and if you click POST an empty request(request has not parameters) is SENT causing the doSubmit to abort  the input step (even if you have approved instead).
@RequirePOST
public HttpResponse doSubmit(StaplerRequest request) throws IOException, ServletException, InterruptedException {
if (request.getParameter("proceed")!=null) {
User user= User.current();
doProceed(request, user);
} else {
doAbort();
}
// go back to the Run console page
return HttpResponses.redirectTo("../../console"); …

[JENKINS-26121] Approver Logged

---

step-api/src/test/java/org/jenkinsci/plugins/workflow/steps/StepConfigTester.java

The eclipse compiler is brain dead and treats
rule.configRoundtrip(FreeStyleProject) as ambiguous.
@reviewbybees

Work around eclipse compiler.

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/parallel/ParallelStepTest.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep/config.jelly

Added an option "failFast: true" to the parallel step options that
will terminate all running branches inside a parallel step if one of the
branches fails.

[JENKINS-26034] add option to fail fast on parallel branch failure.

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java

Added a test for a useful scenario involving orchestration of downstream builds. Note that before this change, commenting out the call to `Executor.interrupt` in `BuildTriggerStepExecution.stop` (dating to work @kohsuke did in July) did not cause test failures; now it does.
@reviewbybees

Parallel build cancel

---

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

After #85 was merged, I now see a [different failure](https://jenkins.ci.cloudbees.com/job/plugins/job/workflow-plugin/org.jenkins-ci.plugins.workflow$workflow-aggregator/1049/testReport/junit/org.jenkinsci.plugins.workflow/WorkflowTest/executorStepRestart/). Again `isBuilding` remains true, and as before we see
```
Started
Running: Allocate node : Start
Still waiting to schedule task
Waiting for next available executor
Resuming build
Resuming build
```
for a while. The duplicated message looks suspicious (hence this patch). Then we get
```
… org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: demo #1 completed: SUCCESS
```
and then we start seeing
```
Started
Running: Allocate node : Start
Still waiting to schedule task
Waiting for next available executor
Resuming build
Resuming …
```

Still trying to diagnose failures on WorkflowTest.executorStepRestart

---

CHANGES.md
README.md
TUTORIAL.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/input/InputStepTest.java
cps-global-lib/src/main/java/org/jenkinsci/plugins/workflow/cps/global/WorkflowLibRepository.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
durable-task-step/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/AfterRestartTask.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
job/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly
pom.xml
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/DefaultStepContext.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/StageStepExecution.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerCancelledCause.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/RunWrapper.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/Rejection.java

Various new APIs can be used, and workarounds removed, once we move to the next LTS baseline. Avoids the need to keep this kind of changes in feature PRs like #37.
@reviewbybees

Update baseline to 1.596.x

---

scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/GitStep.java

Fixes mistake made in #79 which caused the snippet generator to offer
```groovy
git credentialsId: '', url: '…'
```
when no credentials were selected. It should be simply
```groovy
git '…'
```
@reviewbybees

[JENKINS-26085] Handle empty credentialsId

---

support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

Otherwise get [this exception](https://gist.githubusercontent.com/jglick/8bf06c6d002faae48f0f/raw/79da82a92b0dd091b344c6d125a49995941448a5/gistfile1.txt) in 1.607+ due to changes in https://github.com/jenkinsci/jenkins/pull/1596. @reviewbybees

Illegal to call Jenkins.getNode(null)

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/EnvActionImpl.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/EnvironmentExpander.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/DefaultStepContext.java

Docker demo sanity check prior to attempted 1.5 release turned up a regression, which I think was introduced by #41, though possibly by #104. Finally testing this, and also extracting previously duplicated code into a new helper method to make it easier to follow.
Really setting `env.VAR = 'value'` was a poor design to begin with (`withEnv` is better), but it is out there and needs to remain supported.
@reviewbybees

Raise precedence of imperative env.VAR

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/BodyInvoker.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/DefaultStepContext.java

For some purposes it is useful to be able to pass in a `LauncherDecorator` as part of the context of a block step, so as to affect how commands are run within that block. This change makes that possible.
(You could already install a global `LauncherDecorator` extension, which will get called by `Node.createLauncher`, via `DefaultStepContext`.)
In the future `CoreWrapperStep` (#37) could make use of this, though `SimpleBuildWrapper` would first need to do something with its `decorateLauncher` method, along the lines of the change in https://github.com/jenkinsci/jenkins/pull/1634, and I am weary of preparing core patches for the moment.
The comment in the `ReadFileStep` constructor talks about contextual `LauncherDecorator`s, though in the context of _enforced_ decoration for security …

Allow LauncherDecorator to be passed in a step context

---

CHANGES.md
job/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly

[JENKINS-27571](https://issues.jenkins-ci.org/browse/JENKINS-27571)
Copying the `getUpUrl` method from `AbstractBuild` seems pointless, since it does nothing special. (Within a request coming from inside a view, `AbstractItem.getUrl` already includes the view in the URL.)
@reviewbybees

[JENKINS-27571] Non-link in build sidepanel

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java

These changes resolve JENKINS-28179 by ensuring the suffix for concurrent builds is generated by using hudson.slaves.WorkspaceList. On the off change this isn't defined or is an empty string, it uses the previous value (@) as the workspace suffix separator. 
https://issues.jenkins-ci.org/browse/JENKINS-28179

[JENKINS-28179] Workspace suffix should respect hudon.slaves.WorkspaceList property

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildQueueListener.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerAction.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java

[JENKINS-28063](https://issues.jenkins-ci.org/browse/JENKINS-28063)
@reviewbybees

[JENKINS-28063] Handle redundant upstream builds

---

README.md

Jenkins is running on port 8080, demo project with jetty is on 8081.

Change demo link to jenkins

---

CHANGES.md
scm-step/src/main/java/org/jenkinsci/plugins/workflow/steps/scm/GenericSCMStep.java
scm-step/src/main/resources/org/jenkinsci/plugins/workflow/steps/scm/GenericSCMStep/config.jelly
step-api/src/main/java/org/jenkinsci/plugins/workflow/util/StaplerReferer.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java

[JENKINS-28756](https://issues.jenkins-ci.org/browse/JENKINS-28756)
@reviewbybees

[JENKINS-28756] GenericSCMStep.getApplicableDescriptors buglet

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowRunTest.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

[See JENKINS-29221](https://issues.jenkins-ci.org/browse/JENKINS-29221).
@reviewbybees

[FIXED JENKINS-29221] WorkflowRun assigned FlowExecution when execution start fails

---

COMPATIBILITY.md

Fix broken links in documentation (sections that were moved from ```scm-step``` module to COMPATIBILITY.md)

Fix broken links in documentation

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepRestartTest.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

[JENKINS-26761](https://issues.jenkins-ci.org/browse/JENKINS-26761)
Supersedes #136.
@reviewbybees

[JENKINS-26761] WorkflowRun.checkouts sometimes null

---

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

Subsumes #162.
It seems that the fix of #157 obviated the hack introduced in #97. From what I can tell, the only reason we needed access to `Run.id` in advance of basic `Run` deserialization being complete was that the `CpsFlowExecution` used to try to call `Owner.get()` based on the `id` during that actual deserialization, rather than later during `WorkflowRun.onLoad`.
I tried to also get rid of the `LOADING_RUNS` hack by commenting out
```java
LOADING_RUNS.put(key(), this);
```
but that produced an error in `WorkflowTest.executorStepRestart`:
```
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.AssertionError: tried to overwrite demo #1 with demo #1
at org.jenkinsci.plugins.workflow.cps.CpsStepContext.getThreadSynchronously(CpsStepContext.java:234)
at …
```

[JENKINS-27531] Simplified fix

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java

https://issues.jenkins-ci.org/browse/JENKINS-29738
In `TimeoutStep`, the timeout value was initialized when `onResume` was invoked.
For example, in this workflow script:
```
node {
timeout(time: 60, unit: 'SECONDS') {
sleep 10
[Jenkins is restarted] <<<
sleep 50
}
}
```
The expected result of this execution is `ABORTED`:
1. first sleep step, 10 seg
1. second sleep step, 50 seg
1. restart process (safeRestart), enough to exceed 60 seg.

[JENKINS-29738] TimeoutStep restarts the timeout value when onResume method is invoked

---

CHANGES.md
TUTORIAL.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/CpsScmFlowDefinitionTest.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/views/FlowGraphTableAction.java
job/src/main/resources/org/jenkinsci/plugins/workflow/job/views/FlowGraphTableAction/index.jelly

as the action will display all steps that have both run and are running to
call the action "Running steps" is incorrect and at first glance to a user
is incorrect. This changes the name to "Workflow Steps" which is
marginally better.
@reviewbybees

rename 'Running Steps' to 'Workflow Steps'

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

Actually only the patch to `CpsFlowExecution` directly supports checkpoints; the patch to `WorkflowRun` addresses a regression from #149 which I noticed also caused random test failures caught at the same time.
@reviewbybees

Minor changes to support checkpoints

---

multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java

We deny `DELETE` permission to regular users, but during garbage collection of branches the system does do a `Job.delete` which must be allowed.
@reviewbybees

Error in dead branch cleanup

---

pom.xml

[JENKINS-28840](https://issues.jenkins-ci.org/browse/JENKINS-28840) is a nasty deadlock fixed in 1.609.2. It is known to strike functional tests at random, causing them to hang (and this has happened to me during `release:prepare`). This repository configures Surefire to reruns flaky tests, but it does not help here, because `JenkinsRule` currently stops its three-minute test timer _before_ shutting down Jenkins, which is when the deadlock occurs, so there is no recovery.
@reviewbybees

Updating baseline to 1.609.2 to pick up JENKINS-28840 fix

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/stash/StashTest.java
api/src/main/java/org/jenkinsci/plugins/workflow/flow/StashManager.java
basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep.java
basic-steps/src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactUnarchiverStep.java
basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep/help.html
basic-steps/src/main/resources/org/jenkinsci/plugins/workflow/steps/ArtifactUnarchiverStep/config.jelly
demo/repo/Jenkinsfile
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep.java
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/config.jelly
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-excludes.html
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-includes.html
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-name.html
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help.html
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep/config.jelly
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep/help-name.html
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep/help.html

[JENKINS-26942](https://issues.jenkins-ci.org/browse/JENKINS-26942)
A fairly simple solution to the common problem in workflows of needing to save some files temporarily that were created in one node/workspace and get them back later. You could previously do this with `archive`/`unarchive` but the syntax was a little clumsier, and there were unwanted side effects to saving artifacts. (Now `archive` should be used only for deliberately saving artifacts.)
@reviewbybees esp. @jtnord

[JENKINS-26942] Stash files

---

api/src/main/java/org/jenkinsci/plugins/workflow/flow/StashManager.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousNonBlockingStepExecution.java

Needed for `mvn release:perform` on JDK 8.
This used to get checked automatically by the PR builder, but somewhere along the line someone changed to job to use JDK 7. Changed back now.
@reviewbybees

Javadoc fixes

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages.properties
cps/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java

Off the top of my head @cyrille-leclerc, @apemberton, and @gregsymons have gotten tripped up on the steps added by `docker-workflow`, which are not intended to be used from your script. Trying harder to guide users away from these.
(Really want a different UI, at least a form validation warning, maybe a checkbox guarding access to these steps, etc. All of those options seem to require more work than I have time for, due to lack of options in `/lib/form`. This is a quick fix in the interim. CC @tfennelly.)
@reviewbybees esp. @jtnord

Additional warning from StepDescriptor.advanced

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
step-api/src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousNonBlockingStepExecution.java

[JENKINS-30122](https://issues.jenkins-ci.org/browse/JENKINS-30122)
@reviewbybees esp. @amuniz

[JENKINS-30122] AbstractSynchronousNonBlockingStepExecution neglected to pick up the build’s authentication

---

pom.xml

Amends #184. Still building & testing against 1.609.2, but declaring a dependency only on 1.609.1, so the plugins will still be offered in the update center for 1.609.1 users. Desirable until more people have 1.609.2 installed.
(Would be nice to build against 1.609.1 but test against 1.609.2, but I could find no way to do that with Maven: you cannot select different artifact versions for `compile` vs. `test` scope. Deleting some entries from the Surefire classpath and then readding them with a different version might work, but this would cause havoc when running tests in a debugger and source-stepping, etc.)
@reviewbybees

Temporarily declare Jenkins-Version: 1.609.1

---

multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-30222] Multibranch/global var incompatibility

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/WorkflowJobNonRestartingTest.java
api/src/main/java/org/jenkinsci/plugins/workflow/graph/FlowNode.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepAtomNode.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepEndNode.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepStartNode.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/console/WorkflowConsoleLogger.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/console/WorkflowMetadataConsoleFilter.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/console/WorkflowRunConsoleNote.java

[JENKINS-30088](https://issues.jenkins-ci.org/browse/JENKINS-30088)
Note that the first point described in the JIRA issue is fixed in https://github.com/jenkinsci/workflow-plugin/pull/211 which is more focused on the Snippet Generator clean up.
A screenshot showing how the logs are printed given the following script:
```
node {
echo 'Starting!'
stage 'Checkout'
git 'https://github.com/amuniz/maven-helloworld.git'
stage 'Building'
sh 'uname -a'
ws('other-ws') {
echo 'This is another workspace'
}
stage 'Release'
echo 'Releasing...'
}
```
I'm not an UX expert, so any comment on how _metadata_ log lines and the _rest of the build log_ could live better together will be welcome!
@reviewbybees

[JENKINS-30088] Clean up step display in logs

---

COMPATIBILITY.md

The pull request was not merged in time for the 0.4.1 release. I assume it will be in 0.4.2, since it is now in master.

AnsiColorPlugin 0.4.1 is not compatible

---

demo/Dockerfile

I also see `hudson.model.Computer$TerminationRequest` exceptions while the build is running ([see gist](https://gist.github.com/tfennelly/252efe7f9d34b90e14b5) ). These same exceptions happen when I pull and run the latest published image (so is not a regression). The demo runs fine.
I did not update the demo to use v1.10.1 of the workflow plugins, or to use the 1.625.1 jenkins docker image, but I did change and test it locally and it worked fine.

Fix demo image assembly

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java

[JENKINS-30798](https://issues.jenkins-ci.org/browse/JENKINS-30798)
Essentially the same change as #231 but with some additional robustness fixes, and more clearly showing what is being fixed here.
@reviewbybees esp. @recena

[JENKINS-30798] SCMBinder was calling the wrong overload of SCMSource.fetch

---

multibranch/pom.xml
multibranch/src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactoryTest.java

Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/18. Interactively tested using a [reverse proxy](https://hub.docker.com/r/jglick/jenkins-demo-reverse-proxy/) and [this repo](https://github.com/jglick/multibranch-demo) to make sure the encoded slashes were probably passed around.
Also checked that functional test passes on Windows.
@reviewbybees esp. @stephenc

[JENKINS-30744] Updated to use Branch.encodedName

---

cps/pom.xml

These dependencies are available in the update center: `ace-editor:1.0.1` and `jquery-detached:1.1.1`
@reviewbybees especially @tfennelly

ace-editor and jquery-detached have been updated

---

cps/gulpfile.js
cps/package.json
cps/src/main/js/samples.js
cps/src/main/js/workflow-editor.js

[JENKINS-31585](https://issues.jenkins-ci.org/browse/JENKINS-31585)
ACE Editor doesn't support drag resize so this PR uses jQuery UI and it's "resizable" function to accomplish it.

[Fixed JENKINS-31585] Make workflow editor (ACE) resizable.

---

COMPATIBILITY.md

Just noticed that support for workflows was recently merged so updated the `COMPATIBILITY.md` to reflect that.
https://github.com/dblock/jenkins-ansicolor-plugin/pull/54

Update COMPATIBILITY.md; ansicolor is now supported

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/build/BuildTriggerStepTest.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildQueueListener.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java

[JENKINS-31902](https://issues.jenkins-ci.org/browse/JENKINS-31902)
Also took the opportunity to touch up console log display, which was fairly crude.
@reviewbybees

[JENKINS-31902] Fix of interrupt handling for downstream flows

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/stash/StashTest.java
api/src/main/java/org/jenkinsci/plugins/workflow/flow/StashManager.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/config.jelly
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep/help-useDefaultExcludes.html

[JENKINS-31086](https://issues.jenkins-ci.org/browse/JENKINS-31086)
Defaults to true, meaning use Ant default excludes for
DirScanner.Glob. If false, don't use the default excludes, to pick up
files like .gitignore etc.
@reviewbybees

[JENKINS-31086] Add useDefaultExcludes option to stash

---

durable-task-step/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

Not clear if this is a fix for all cases of [JENKINS-31769](https://issues.jenkins-ci.org/browse/JENKINS-31769), but at least one thing I could reproduce. Using a slave
```xml
<?xml version='1.0' encoding='UTF-8'?>
<slave>
<name>slow</name>
<description></description>
<remoteFS>…</remoteFS>
<numExecutors>5</numExecutors>
<mode>NORMAL</mode>
<retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
<launcher class="org.jenkinci.plugins.mock_slave.MockSlaveLauncher" plugin="mock-slave@1.8">
<latency>10</latency>
<bandwidth>0</bandwidth>
</launcher>
<label></label>
<nodeProperties/>
<userId>anonymous</userId>
</slave>
```
and script
```groovy
def go() {
for (int i = 0; i < 100; i++) {
echo "iteration #${i}"
sh "sleep ${new Random().nextInt(5) + 1}"
}
}
node('slow') {
def branches = …
```

[JENKINS-31769] Prevent some problems with hanging sh steps

---

durable-task-step/src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep/help.html

Amends help in #211 so CC @amuniz. `-xe` are passed only if an explicit interpreter is _not_ defined. [reference](https://github.com/jenkinsci/durable-task-plugin/blob/b27495f9190939590660c29971317ddcd2c774cf/src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java#L70-L73)
@reviewbybees

Correcting help for the shell step.

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/scm/GitStepTest.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java

Marked as @Ignore until
https://github.com/jenkinsci/git-plugin/pull/372 is merged and
released, at which point we'll need to bump the git plugin version as well.

[JENKINS-29326] Don't add duplicate BuildData (downstream)

---

cps-global-lib/README.md

EchoStep.message expects class java.lang.String but received class java.lang.Integer
No such property: name for class: acme

Fix README for vars/acme.groovy

---

CHANGES.md
aggregator/src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
cps/src/main/resources/org/jenkinsci/plugins/workflow/cps/EnvActionImpl/Binder/help.jelly
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java

All credit goes to #246, most of this is copied verbatim from that patch.
I basically just corrected the source to actually take the executor number.
I couldn't get the tests to run properly locally, so I am pushing here to get it picked up by CI.

Add EXECUTOR_NUMBER to build env

---

cps/src/test/java/org/jenkinsci/plugins/workflow/cps/AbstractCpsFlowTest.java

Follow-up to #277, trying to solve remaining failures like [this](https://jenkins.ci.cloudbees.com/job/plugins/job/workflow-plugin/org.jenkins-ci.plugins.workflow$workflow-aggregator/2040/testReport/junit/org.jenkinsci.plugins.workflow/WorkflowJobNonRestartingTest/sandbox/).
@reviewbybees

[JENKINS-30395] Extend workaround to subclasses of AbstractCpsFlowTest

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java

Confuses me with `No such DSL method step found among [...`

Escape method name.

---

cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

After merging #213, have been seeing build timeouts apparently in `ScalabilityTest`. Managed to capture a thread dump from one; redacted:
```
=== Starting manySteps(org.jenkinsci.plugins.workflow.ScalabilityTest)
Jan 12, 2016 11:02:51 AM org.jvnet.hudson.test.JenkinsRule$1 run
WARNING: Test timed out (after 180 seconds).
"Executing manySteps(org.jenkinsci.plugins.workflow.ScalabilityTest)" Id=1 Group=main WAITING on hudson.model.queue.FutureImpl@590952dd
at java.lang.Object.wait(Native Method)
-  waiting on hudson.model.queue.FutureImpl@590952dd
at java.lang.Object.wait(Object.java:502)
at hudson.remoting.AsyncFutureImpl.get(AsyncFutureImpl.java:73)
at org.jvnet.hudson.test.JenkinsRule.assertBuildStatusSuccess(JenkinsRule.java:1109)
at …
```

Avoid scheduling executor tasks for getThreadSynchronously

---

job/src/main/java/org/jenkinsci/plugins/workflow/job/AfterRestartTask.java

[JENKINS-28649] Api call with AfterRestartTask throws ExportedBean annotation exception

---

multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/getting-started.jelly
multibranch/src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory/getting-started.jelly

@reviewbybees 
This will PR can happen independently, but will result in integration with improved information pages in the circumstance no items are present in multibranch & organization folders: https://github.com/jenkinsci/branch-api-plugin/pull/17

Add getting-started pages for branch sources

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
aggregator/src/test/java/org/jenkinsci/plugins/workflow/ScalabilityTest.java
aggregator/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java
aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/EchoStepTest.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputAction.java
support/src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution/PlaceholderTask/PlaceholderExecutable/executorCell.jelly

Partly follows up #301, plus some other fixes inspired by looking at a thread dump from a `linearFlow` failure. Per-commit messages have detailed justifications.
Now subsumes #310.
@reviewbybees

Miscellaneous fixes for acceptance test failures

---

api/src/main/java/org/jenkinsci/plugins/workflow/graph/FlowNode.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java

[JENKINS-30088](https://issues.jenkins-ci.org/browse/JENKINS-30088)
Before:
```
[Pipeline] node {
[Pipeline] Execute sub-workflows in parallel : Start
[Pipeline] [firstBranch] parallel {: Parallel branch: firstBranch
[Pipeline] [secondBranch] parallel {: Parallel branch: secondBranch
[Pipeline] [firstBranch] writeFile
[Pipeline] [firstBranch] stash
```
After:
```
[Pipeline] node {
[Pipeline] Execute sub-workflows in parallel : Start
[Pipeline] [firstBranch] parallel { (Branch: firstBranch)
[Pipeline] [secondBranch] parallel { (Branch: secondBranch)
[Pipeline] [firstBranch] writeFile
[Pipeline] [firstBranch] stash
```
@reviewbybees

Minor changes to console logs forgotten in JENKINS-30088 fix

---

durable-task-step/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java

[JENKINS-32547](https://issues.jenkins-ci.org/browse/JENKINS-32547)
WinRM is slow. Like, really, __really__ slow. So slow, that streaming
back the results of a `DurableTaskStep` can easily take more than
the previously set timeout of 3 seconds. This would cause even
super-simple builds steps like `bat 'echo TEST'` to run for very
long times (in some cases more than 20 minutes).
Bumping the internal timeout of a `DurableTaskStep` to 10 seconds seems
to fix any issues with slaves connected over WinRM, and I've not seen
a single `InterruptedException` show up in the log files.

[FIXED JENKINS-32547] Make `durable-task-step` play nicely with WinRM connections

---

support/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/POSTHyperlinkNote.java

Fixes a trivial but longstanding annoyance: that the console log scrolls back up to the top of the screen when you click on _Proceed_ from an `input` step (for example).
The comment about `crumb` was deleted because I confirmed that it works, due to [this hack](https://github.com/jenkinsci/jenkins/blob/1f89b5a9096f8d4946c1797e79ca5e2f494175ee/war/src/main/webapp/scripts/prototype.js#L1535-L1541).
@reviewbybees

Fixed onclick handler

---

aggregator/pom.xml

Reverts this part of #296 now that 1.13 has been released.
@reviewbybees esp. @recena

Remove “formerly known” text

---

cps-global-lib/README.md

People will mostly be using global lib from a non `mvn hpi:run` debug mode and including http://server/jenkins was thus confusing.
@reviewbybees

Fix instructions to omit /jenkins path

---

COMPATIBILITY.md

Build Monitor can display Jenkins Workflow jobs since version 1.6+build.159

Build Monitor supports Jenkins Workflow jobs

---

job/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java

Mistake in #213 which leads to junk in `build.xml` in 1.13.
@reviewbybees

logPrefixCache was not intended to be serialized

---

aggregator/src/test/java/org/jenkinsci/plugins/workflow/steps/SleepStepTest.java
cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java

`CpsClosure2.sleep` was already `@Whitelisted`, but this one (used _outside_ blocks/closures) was forgotten.
@reviewbybees

Simple form of sleep step would fail in sandbox

---

COMPATIBILITY.md

added stashNotifier plugin as not compatible (cf. [issue#92](https://github.com/jenkinsci/stashnotifier-plugin/issues/92))

COMPATIBILITY.md update for stashNotifier

---

cps/pom.xml

The jQuery plugin was bloated due to a bad assembly. See [JENKINS-33245](https://issues.jenkins-ci.org/browse/JENKINS-33245).
@jenkinsci/code-reviewers @reviewbybees

Use repackaged jQuery HPI

---

COMPATIBILITY.md

Since release 0.5.0 of aws-lambda-plugin compatibility has been added for Pipeline.

Added aws-lambda-plugin to compatibility.md

---

step-api/src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
step-api/src/test/java/org/jenkinsci/plugins/workflow/structs/DescribableHelperTest.java

[JENKINS-32925](https://issues.jenkins-ci.org/browse/JENKINS-32925)
To prevent stack overflows, especially in the Multiple SCMs case, track the subtypes to make sure the type isn't trying to discover itself.  When that case is detected, don't log, and return back up the stack.  This will only prevent duplication vertically, not horizontally.
@reviewbybees  esp @jglick & @abayer

[JENKINS-32925] Add tracking to prevent stack overflows

---

multibranch/pom.xml
multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Verifies https://github.com/jenkinsci/cloudbees-folder-plugin/pull/42 in context. Without fix, not only does the test fail, but the `IllegalStateException` can be observed in the log.
@reviewbybees

[JENKINS-32179] Integration test

---

multibranch/pom.xml
multibranch/src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java

Downstream of https://github.com/jenkinsci/branch-api-plugin/pull/32.
@reviewbybees

[JENKINS-32670] Integration test

---

pom.xml

Pick up yesterday’s LTS release, so that we no longer suffer from the bug fixed in https://github.com/jenkinsci/jenkins/pull/1989, which gravely affects Pipeline build resumption.
Still waiting for `jenkins:1.642.3` to appear in Docker Hub.
@reviewbybees

Switch baseline to 1.642.3

---

COMPATIBILITY.md

The plugin provides several build steps and post-build actions:
Builder: Test[Package|Project|Folder]Builder, Start[ET|TS]Builder, Stop[ET|TS]Builder
Publisher: [ATX|ETLog|JUnit|ReportGenerator|TRF]Publisher

[JENKINS-31999] Adding ecutest-plugin to COMPATIBLITY.md

---

COMPATIBILITY.md

OC-cloud has been supported since 1.7.5 and 1.8.3
@reviewbybees - esp @stephenc who did the work and didn't note it :-)

note that operations-center-cloud was supported.

---

COMPATIBILITY.md

According to [JENKINS-27302](https://issues.jenkins-ci.org/browse/JENKINS-27302)

[JENKINS-27302] Clover is compatible with Pipeline since 4.6.0

---

README.md

The usage guidance of the [jenkins-workflow](http://stackoverflow.com/questions/tagged/jenkins-workflow) tag on StackOverflow recommends using tag [jenkins-pipeline](http://stackoverflow.com/questions/tagged/jenkins-pipeline) instead.

Update tag name for StackOverflow

---

COMPATIBILITY.md

https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.11 released with
https://github.com/jenkinsci/stashnotifier-plugin/issues/92 resolved by
https://github.com/jenkinsci/stashnotifier-plugin/pull/115

Stash Notifier supports pipeline as of 1.11

---

TUTORIAL.md

The code had already been updated, but the explanation still contained references to `archive` and `unarchive`.

TUTORIAL: Update `archive` to `stash` in explanation of multiple threads code

---

COMPATIBILITY.md

Version 2.1.0 of the JaCoCo Plugin added Pipeline compatiblity.
Tested successfully.

[JENKINS-27120] Mark JaCoCoPublisher as compatible

---

COMPATIBILITY.md

PR 55 (https://github.com/jenkinsci/cobertura-plugin/pull/55)
Signed-off-by: Alan Zaffetti <alan.zaffetti@ibm.com>

[JENKINS-30700] Add CoberturaPublisher to compatability note

---

TUTORIAL.md

I had an issue when working with Build parameters, https://github.com/jenkinsci/pipeline-plugin/blob/master/TUTORIAL.md#build-parameters is confusing. I
found the solution in [JENKINS-40235](https://issues.jenkins-ci.org/browse/JENKINS-40235) and added details here: http://stackoverflow.com/a/41276956/1092815

Build parameters not groovy variables anymore

---

COMPATIBILITY.md

I wasn't sure if this belongs in "Misc" or the "Build wrappers" section, and I also guessed a little bit on BuildPreferenceJobProperty; that's the class that was persisted in the config.xml of the job so it seemed right.

mark scoring-load-balancer job-level preferences as unsupported

---

COMPATIBILITY.md

I added documentation links where it was possible. I hope everybody is fine with such format improvement.
- TCB plugin support Pipeline starting from 2.0
- EnvInject offers partial support
- Job Restrictions offers partial support (95% done, heh)
- Release plugin offers the `release()` step
- Ownership plugin now has documentation
@reviewbybees @jglick @abayer

Update COMPATIBILITY for several plugins.

---

COMPATIBILITY.md

Updated pipeline support for plugins: HttpRequest, PerformancePublisher, HockeyappRecorder, ghprb and test-results-analyzer. Checked support via Jira, PRs, changelogs. Confirmed HttpRequest by checking syntax snippet.
@reviewbybees

[JENKINS-32263] [JENKINS-32650] [JENKINS-33841] [JENKINS-33310] [JENKINS-26591] [JENKINS-30522] Updated support status for several plugins

---

COMPATIBILITY.md

Support introduced in https://github.com/jenkinsci/plot-plugin/pull/32
`2.0.0` released and [plugin wiki](https://wiki.jenkins.io/display/JENKINS/Plot+Plugin) updated.

Mention plot plugin Pipeline compatibility

---

COMPATIBILITY.md

Hi, 
I want to update compatibility info in 2 plugins:
1) Performance plugin https://wiki.jenkins.io/display/JENKINS/Performance+Plugin
This plugin has build step: https://github.com/jenkinsci/performance-plugin/blob/master/src/main/java/hudson/plugins/performance/build/PerformanceTestBuild.java#L43
and post-build step (publisher): https://github.com/jenkinsci/performance-plugin/blob/master/src/main/java/hudson/plugins/performance/PerformancePublisher.java#L78
Pipeline supported since version 3.1 (released 2nd of June, 2017)
2) BlazeMeter plugin https://wiki.jenkins.io/display/JENKINS/blazemeter+Plugin
This plugin has build step: https://github.com/jenkinsci/blazemeter-plugin/blob/master/src/main/java/hudson/plugins/blazemeter/PerformanceBuilder.java#L47
Pipeline supported since version …

[JENKINS-32650] update Performance plugin and BlazeMeter plugin compatibility

---

COMPATIBILITY.md

As of Coverity plugin version 1.10.0 there is support for pipeline. We created a new publisher step instead of working pipeline support into the existing `CoverityPublisher`. Also added a `SimpleBuildWrapper` to use a `CoverityToolInstallation` on the path.

Updated support status for Coverity Plugin
